Module2 task1
htmlacademy-adaptive/1390101-cat-energy-27 pull request #2
Opened 2022-11-30 12:16 UTC by Kris-js

2022-11-30 18:35 UTC, wrgraff requested changes
С элементами форм хорошо справилась.
Но есть и ошибочки, некоторые — повторяются, обрати внимание на подписи вне ссылок и лишние теги в разметке.
Вообще, не нужно стараться разметку делать больше, чем сейчас нам требуется для семантики.

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +      <button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню</span></button>
Я для лучшей читаемости рекомендовал бы писать вот так:
```suggestion
      <button class="main-nav__toggle" type="button">
        <span class="visually-hidden">Открыть меню</span>
      </button>
```

Все-таки находить тег внутри другого тега на одной строке может быть немного неудобно

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +          <a href="">
У логотипа у тебя нет `href`, а тут есть.
Надо или делать переход страницы на саму себя, или не делать, поэтому выбирай

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +          <a href="">
У тебя же есть эта страница, надо добавить переход

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +          <a href="">
Эта страница тоже есть

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +        <h2 class="visually-hidden">
Как по мне, так вполне можно использовать основной заголовок прямо здесь

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +          похудение
Почему с маленькой буквы?

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +        <img class="selection__image" src="" alt="Кэт">
Что за описание такое `alt="Кэт"`? Как невидящий по нему что-то поймет?

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +        <a class="selection__button" href="#">подобрать программу</a>
Так мы все-таки используем для заглушки пустоту или решетку?

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +          похудение
Не только здесь эта проблема.
Если так написано в макете — это не задумка, это руки кривые у автора макета. А нам надо писать нормально, с большой буквы

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +        <a class="selection__button" href="#">подобрать программу</a>
При чем, тут не должно быть заглушки, не забывай прочитать [ТЗ](https://up.htmlacademy.ru/adaptive/27/project/cat-energy#cat-energy-4-2)

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +      <div class="offer__wrapper">
А зачем нам 2 обертки?
До этого я так видел, что обертка это идентичный элемент в каждом из блоков, и он будет использоваться строго для центрирования и уже внутри строить сетку. А тут не так. Точно ли стоит делать различный подход в этом вопросе?

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +          </li>
Зачем нам номера в разметке, почему их не расставить как декор через CSS?
Заодно можно избавиться от параграфов и сделать куда более чистую разметку

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +    <section class="slider">
До этого обертки были везде. А тут?

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +    <section class="slider">
Странное название у блока: `slider`.
Слайдер там только на котах самих. Остальное с ним никак и не связано.
Это `slider-cat` должен быть слайдером, а весь блок чем-то еще

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +          </div>
`<dt>` — description term, то есть термин.
`<dd>` — description definition, то есть определение.

Здесь у нас не совсем определения, а скорее имя (термин) и значение (определение).
Что больше похоже на термин/имя: "снижение веса" или "5 кг"?

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +            <dt class="slider__description-statistics">5 КГ</dt>
```suggestion
            <dt class="slider__description-statistics">5 кг</dt>
```

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +            <img src="">
`alt` же уже можно написать?

2022-11-30 18:35 UTC, arturtrifonov commented on source/index.html
> +          <div class="slider-cat__image slider-cat__image--previous">
Наша задача сейчас — сделать смысловую разметку. Откуда столько дивов: ты уже точно предугадываешь реализацию?

2022-11-30 18:35 UTC, wrgraff commented on source/index.html
> +          <span class="visually-hidden">Логотип Кэт Энерджи</span>
Зачем нужен скрытый текст снаружи ссылки?

2022-11-30 18:35 UTC, wrgraff commented on source/index.html
> +        <div class="page-footer__logo">
Зачем тут этот див? Ты уже знаешь, что он необходим для верстки?

2022-11-30 18:35 UTC, wrgraff commented on source/index.html
> +              </a>
Тут тоже почему-то подписи к ссылкам повылетали из них. Мы же вроде бы обращали на это внимание при работе над нашим макетом?

2022-11-30 18:35 UTC, wrgraff commented on source/index.html
> +            <img class="copyright__link-developer" src=""></img>
Сразу же надо задавать картинкам описания

2022-11-30 18:35 UTC, wrgraff commented on source/catalog.html
> +    <h1 class="main-container-title">
Какое-то название странное...
Зачем заголовок отдельным БЭМ-блоком сделан вообще?

2022-11-30 18:35 UTC, wrgraff commented on source/catalog.html
> +      <div class="product">
Что за обертка, откуда взялась, зачем нужна, почему отдельным блоком сделана?

2022-11-30 18:35 UTC, arturtrifonov commented on source/catalog.html
> +        </h1>
Второй заголовок первого уровня, получается

2022-11-30 18:35 UTC, arturtrifonov commented on source/catalog.html
> +            </dl>
Довольно странно называть `specifications-definition` слово "Масса". Потому что, для начала, "definition" это `<dd>`, он так и сокращен от "description definition".

Потом, ты не делаешь это в нейминге, но обрати внимание, что у тебя `specifications` работает почти как отдельный БЭМ-блок. Он имеет общее название на обертке, а дальше через `-` имеет элементы. Если такое вылезает в коде, то просто делай отдельный блок, не надо эту имитацию использовать.

```suggestion
            <dl class="product-card__specifications specifications">
              <dt class="specifications__definition">Масса</dt>
              <dd class="specifications__meaning">500 г</dd>
              <dt class="specifications__definition">Вкус</dt>
              <dd class="specifications__meaning">Курица</dd>
              <dt class="specifications__definition">Цена</dt>
              <dd class="specifications__meaning">700 Р.</dd>
            </dl>
```

2022-11-30 18:35 UTC, wrgraff commented on source/form.html
> +    <h1 class="main-container__title">
А в каталоге это не элемент был. А тут элемент.
Тут логичнее.

2022-11-30 18:35 UTC, wrgraff commented on source/form.html
> +        анкета
```suggestion
        Анкета
```

2022-11-30 18:35 UTC, arturtrifonov commented on source/form.html
> +          <fieldset class="order-form__group form-programm">
```suggestion
          <fieldset class="order-form__group form-program">
```

2022-11-30 18:35 UTC, arturtrifonov commented on source/form.html
> +                  <span class="radio__control-mark"></span>
Да нафиг этот `control-mark` нам не нужен, тем более на этапе разметки

2022-11-30 18:35 UTC, arturtrifonov commented on source/form.html
> +    </section>
Как у нас так оказалось 3 закрывающих тега на одном уровне?
Так не бывает. Где-то закрался косяк. Вот я даже в валидатор загрузил, и он выдал кучу ошибок.

2022-12-01 04:12 UTC, Kris-js commented on source/index.html
> +      <button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню</span></button>
согласна, исправила

2022-12-01 04:14 UTC, Kris-js commented on source/index.html
> +          <a href="">
Решила убрать, чаще активная страница не кликабельна

2022-12-01 12:32 UTC, Kris-js commented on source/index.html
> +          <a href="">
Добавила

2022-12-01 12:32 UTC, Kris-js commented on source/index.html
> +          <a href="">
Добавила

2022-12-01 12:34 UTC, Kris-js commented on source/index.html
> +        <h2 class="visually-hidden">
Думала вынести, но кода получается больше в итоге. Перенесла заголовок в секцию.

2022-12-01 12:42 UTC, Kris-js commented on source/index.html
> +          похудение
Поняла, поменяла

2022-12-01 12:46 UTC, Kris-js commented on source/index.html
> +        <img class="selection__image" src="" alt="Кэт">
Дополнила

2022-12-01 12:53 UTC, Kris-js commented on source/index.html
> +        <a class="selection__button" href="#">подобрать программу</a>
Добавила везде заглушки

2022-12-01 13:22 UTC, Kris-js commented on source/index.html
> +        <a class="selection__button" href="#">подобрать программу</a>
Сделала

2022-12-01 20:26 UTC, Kris-js commented on source/index.html
> +      <div class="offer__wrapper">
Мы за единообразие, убрала

2022-12-01 20:30 UTC, Kris-js commented on source/index.html
> +          </li>
Согласна, убрала

2022-12-01 20:32 UTC, Kris-js commented on source/index.html
> +    <section class="slider">
Тоже добавила

2022-12-01 20:35 UTC, Kris-js commented on source/index.html
> +    <section class="slider">
Исправила

2022-12-01 20:43 UTC, Kris-js commented on source/index.html
> +          </div>
Поняла, поменяла местами. Снижение веса может быть и на 3кг.

2022-12-01 20:44 UTC, Kris-js commented on source/index.html
> +            <dt class="slider__description-statistics">5 КГ</dt>
+

2022-12-01 20:46 UTC, Kris-js commented on source/index.html
> +            <img src="">
Прописала

2022-12-01 20:47 UTC, Kris-js commented on source/index.html
> +          <div class="slider-cat__image slider-cat__image--previous">
Я просто помню, как мы делали обертку, что-бы обрезать картинки

2022-12-01 20:54 UTC, Kris-js commented on source/index.html
> +          <span class="visually-hidden">Логотип Кэт Энерджи</span>
Перенесла внутрь

2022-12-01 21:00 UTC, Kris-js commented on source/index.html
> +        <div class="page-footer__logo">
Убрала

2022-12-01 21:09 UTC, Kris-js commented on source/index.html
> +              </a>
Поправила

2022-12-01 21:11 UTC, Kris-js commented on source/index.html
> +            <img class="copyright__link-developer" src=""></img>
Добавила

2022-12-01 21:12 UTC, Kris-js commented on source/catalog.html
> +    <h1 class="main-container-title">
Поправила

2022-12-01 21:19 UTC, Kris-js commented on source/catalog.html
> +      <div class="product">
Исправила

2022-12-02 06:54 UTC, Kris-js commented on source/catalog.html
> +        </h1>
Перенесла заголовок, т.к. происходит дублирование одного заголовка

2022-12-02 07:10 UTC, Kris-js commented on source/catalog.html
> +            </dl>
Поняла, исправила

2022-12-02 07:20 UTC, Kris-js commented on source/form.html
> +          <fieldset class="order-form__group form-programm">
поправила

2022-12-02 07:40 UTC, Kris-js commented on source/form.html
> +                  <span class="radio__control-mark"></span>
Убрала

2022-12-02 07:49 UTC, Kris-js commented on source/form.html
> +    </section>
поправила

2022-12-03 19:16 UTC, wrgraff commented on source/catalog.html
> +          Каталог продукции
Ты совсем удалила тег, а я говорил о том, чтобы удалить именно адрес в нем.
Если у ссылки удалить `href`, то она перестанет быть кликабельной. Более того, из CSS мы можем с помощью псевдокласса выделить адрес именно  с действующей ссылкой (например, чтобы не писать стили наведения для ссылок без адресов). Это псевдокласс `:link`.

Тег конечно тоже иногда можно удалять, но вот оформление меню это изрядно затруднит.

2022-12-03 19:16 UTC, wrgraff commented on source/index.html
> +          <a href="">
Нет такого, кстати, чтобы чаще была не кликабельна. Довольно часто они вполне себе кликабельны и только на вид отличаются. Нет никаких толковых аргументов против того, чтобы на странице была ссылка на саму себя.

2022-12-03 20:17 UTC, wrgraff requested changes
Надо еще поправить, повылазило тут кой-чего

2022-12-03 20:17 UTC, arturtrifonov commented on source/index.html
> +          Слоган Кэт Энерджи
Непонятно, что дает этот заголовок. Как он описывает содержимое секции?

2022-12-03 20:17 UTC, arturtrifonov commented on source/index.html
> +        <h2 class="visually-hidden">
Так он и вынесен. И тебе надо будет встраивать рядом с картинкой этот заголовок, он должен будет переполняться. Как ты планируешь все это делать при условии, что он где-то снаружи? Это же будет неудобно.

2022-12-03 20:17 UTC, arturtrifonov commented on source/index.html
> +        <img class="selection__image" src="#" alt="Рекламное изображенеие кота">
Смотри, описание должно быть такое, чтобы слепой человек понял, что там изображено. То, что там "рекламное изображение" — что это дает? Тем более, там не кот, там банка с кормом!
Либо нужно описать что там, либо вообще убирать из разметки, так как если изображению внятного описания нет, то оно значит нам ничем и не полезно кроме "рюшечек".

2022-12-03 20:17 UTC, arturtrifonov commented on source/index.html
> +              <img src="#" alt="Изображение кота после представленного питания">
Незрячий конечно разницу саму не увидит.

Ну и так как мы пишем со стороны продукта, то можно писать "нашего питания" или "питания Кэт Энерджи", что-то такое.
Но это я конечно уже совсем в мелочи погружаюсь и ux-писательство какое-то

2022-12-03 20:17 UTC, arturtrifonov commented on source/index.html
>                </a>
Я не понимаю логику этой разметки. Как будет создана иконка? Через тег svg? Зачем нам модификатор тогда, что он делать будет, если все необходимое будет создано через svg?
Если это будет псевдоэлмент, с расставленными через модификаторы картинками, то зачем нам svg-тег?

2022-12-03 20:17 UTC, arturtrifonov commented on source/index.html
> +                <span class="visually-hidden">Мы в Инстаграме</span>
Обрати внимание, что в макете нет ни Инстаграма, ни Фейсбука

2022-12-03 20:17 UTC, wrgraff commented on source/index.html
> +              <dt class="example__description-text">снижение веса</dt>
Ты поменяла местами, но по правилам `<dt>` должен строго идти перед `<dd>`. Так что термин должен идти первым.

2022-12-03 20:17 UTC, wrgraff commented on source/index.html
> +              <dd class="example__description-statistics">60 ДНЕЙ</dd>
Ну это не только к "кг" относился коммент, а вообще ко всему.

```suggestion
              <dd class="example__description-statistics">60 дней</dd>
```

2022-12-03 20:17 UTC, wrgraff commented on source/index.html
> +          <div class="slider-cat__image slider-cat__image--previous">
Ну, вообще мы верстаем с нуля, и что было тогда уже не так важно.
Кроме того, даже дизайн слайдера уже поменялся с тех пор. Так что повторять то решение смысла нет особо.

2022-12-03 20:17 UTC, wrgraff commented on source/index.html
> +            <img class="copyright__link-developer" src="#" alt="Логотип HTML Academy"></img>
Погоди, а с каких пор у `<img>` появилась закрывающая половина тега?
```suggestion
            <img class="copyright__link-developer" src="#" alt="Логотип HTML Academy">
```

2022-12-03 20:17 UTC, wrgraff commented on source/catalog.html
> +          Карточки товара
Одного товара?

2022-12-05 09:22 UTC, Kris-js commented on source/index.html
> +          <div class="slider-cat__image slider-cat__image--previous">
Убрала обертки

2022-12-05 09:24 UTC, Kris-js commented on source/catalog.html
> +          Каталог продукции
Добавила ссылку и заглушку вместо адреса

2022-12-05 09:37 UTC, Kris-js commented on source/index.html
> +        <img class="selection__image" src="#" alt="Рекламное изображенеие кота">
Убрала

2022-12-05 09:42 UTC, Kris-js commented on source/index.html
> +              <img src="#" alt="Изображение кота после представленного питания">
Ага изменила, думала как правильно описать)

2022-12-05 09:43 UTC, Kris-js commented on source/index.html
>                </a>
Через свг, он же меняется по стайлгайду. Модификатор убрала

2022-12-05 09:47 UTC, Kris-js commented on source/index.html
> +                <span class="visually-hidden">Мы в Инстаграме</span>
Поменяла)

2022-12-05 09:48 UTC, Kris-js commented on source/index.html
> +              <dt class="example__description-text">снижение веса</dt>
Поменяла

2022-12-05 09:59 UTC, Kris-js commented on source/index.html
> +              <dd class="example__description-statistics">60 ДНЕЙ</dd>
Исправила

2022-12-05 10:00 UTC, Kris-js commented on source/index.html
> +            <img class="copyright__link-developer" src="#" alt="Логотип HTML Academy"></img>
Ой

2022-12-05 10:01 UTC, Kris-js commented on source/catalog.html
> +          Карточки товара
Множества)

2022-12-05 20:24 UTC, arturtrifonov commented on source/catalog.html
> +          <a href="#">
Опять не то =(
Смотри, у нас несколько вариантов адресов:
1. `<a href="page.html">` или `<a href="./page.html">`
  Используется когда мы знаем, что это должна быть рабочая ссылка и она у нас есть, мы можем поставить на нее ссылку.
2. `<a href="#">` или `<a href="">`
  Используется, когда мы знаем, что это должна быть рабочая ссылка, но адреса мы ее не знаем и потому не можем его поставить. Чтобы ссылка оставалась рабочей, мы ставим заглушку или ничего.
3. `<a>`
  Используется, когда мы не хотим, чтобы ссылка работала, например — ссылка на текущую страницу.
  
Почему это ошибка?
Потому что у нас есть страница каталога, должен быть вариант 1 или 3.

2022-12-05 20:24 UTC, arturtrifonov commented on source/index.html
> +        <h2 class="selection__title">
Так он наверное должен первого уровня быть? Не может быть страницы без `<h1>`

2022-12-05 20:24 UTC, wrgraff commented on source/index.html
> +        <img class="selection__image" src="#" alt="Рекламное изображенеие кота">
Я имел ввиду — убрать картинку и не использовать как контентную, так как отсутствие внятного описания наталкивает на мысль, что картинка не нужна для контента.
Если она остается, то описание должно быть. И внятное.

2022-12-05 20:28 UTC, wrgraff commented on source/catalog.html
> +          Каталог продукции
Вот заглушка то ну откуда взялась, если ссылка должна быть не кликабельна

2022-12-06 06:11 UTC, Kris-js commented on source/index.html
> +        <h2 class="selection__title">
Ага, исправила!

2022-12-06 12:06 UTC, wrgraff approved these changes

2022-12-06 12:07 UTC, merged