Стилизация
htmlacademy-adaptive/1390101-cat-energy-27 pull request #3
Opened 2022-12-09 15:21 UTC by Kris-js

---
:mortar_board: [Стилизация](https://up.htmlacademy.ru/adaptive/27/user/1390101/tasks/7)

2022-12-10 17:40 UTC, wrgraff requested changes
Обращай внимание, прошел ли пулл-реквест тестирование. Можешь заранее увидеть и исправить некоторые ошибки.

Отступы конечно в большинстве случаев поставлены неправильно. Предлагаю пока оставить и начнем их менять и выправлять на сетках.

2022-12-10 17:40 UTC, arturtrifonov commented on .stylelintrc
> +    "at-rule-no-unknown": null
Так, а для чего нам править линтер?
Мы должны работать с тем, что нам выдали и не править правила под себя.

2022-12-10 17:40 UTC, arturtrifonov commented on source/form.html
> +          <legend class="form-group__title form-options__title">Дополнительно</legend>
Заголовок не находится внутри блока `form-group` и не может быть его элементом

2022-12-10 17:40 UTC, arturtrifonov commented on source/form.html
> +          <button class="button form__button" type="submit">Отправить заявку</button>
В других местах у тебя встречается сперва класс элемента, а потом класс блока.
Нужно писать в едином стиле.

2022-12-10 17:40 UTC, arturtrifonov commented on source/index.html
>          </h2>
Если добавляем обертку, то и отступы необходимо править для тех элементов, что оказываются в ней
```suggestion
        <div class="offer__inner">
          <h2 class="offer__title">
            Похудение
          </h2>
```

2022-12-10 17:40 UTC, arturtrifonov commented on source/index.html
> +        <div class="offer__inner">
Ума не приложу зачем нам сейчас, до того как мы приступаем к сеткам, делать дополнительные обертки.
Наша задача — цвета, фоны, рамки. Паддинги и маргины — по возможности

2022-12-10 17:40 UTC, arturtrifonov commented on source/sass/style.scss
> +@import "./blocks/copyright.scss";
Не стоит делать группировку по страницам. Ну вот например:
`./blocks/site-list.scss` — это блок, относящийся только к главной странице? Нет, навигация у нас есть на всех страницах.
И любой блок может оказаться на какой-то другой странице. Блок карты, слайдер с примером — что угодно. В результате группировка будет только путать и мешать искать нужный блок.

2022-12-10 17:40 UTC, arturtrifonov commented on source/sass/global/fonts.scss
> +}
`oswaldmedium.woff2` — в названии шрифта есть указание на толщину Medium.
Какой вес указан [в таблице](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#common_weight_name_mapping) для такого имени?

2022-12-10 17:40 UTC, arturtrifonov commented on source/sass/global/fonts.scss
> +    url("../../fonts/oswald/oswaldregular.woff") format("woff");
Путь к файлу указан неверно.
Ты указываешь от текущего файла, а нужно — от собранного css-файла.

2022-12-10 17:40 UTC, arturtrifonov commented on source/sass/global/fonts.scss
> +  font-family: "oswald";
Обычно все-таки имена шрифтов пишут с заглавной буквы
```suggestion
  font-family: "Oswald";
```

2022-12-10 17:40 UTC, arturtrifonov commented on source/sass/global/global.scss
> +  color: #000000;
У нас же есть переменные для этих цветов (ну или можно вообще опустить, и так текст черный, а фон белый)

2022-12-10 17:40 UTC, arturtrifonov commented on source/sass/global/variables.scss
> +$color-green-1000: #68b738;
1000? Думаешь, он настолько темный?

2022-12-10 17:40 UTC, arturtrifonov commented on source/sass/global/variables.scss
> +$color-white: #ffffff;
По-моему, было бы логичнее наоборот:
```suggestion
$color-white: #ffffff;
$color-grey-100: #e6e6e6;
$color-grey-150: #e7e7e7;
$color-grey-200: #f2f2f2;
$color-grey-300: #d9d9d9;
$color-grey-400: #eaeaea;
$color-grey-600: #444444;
$color-grey-700: #222222;
$color-grey-900: #111111;
$color-black: #000000;
```

2022-12-10 17:40 UTC, wrgraff commented on source/sass/global/variables.scss
> +$font-second: lato, arial, sans-serif;
```suggestion
$font-main: oswald, Arial, sans-serif;
$font-second: lato, Arial, sans-serif;
```

2022-12-10 17:40 UTC, wrgraff commented on source/sass/global/button.scss
> +  padding: 10px 109px;
Вспомни, как мы на тренировочном сайте делали кнопки: как у нас там указывается ширина для них?
И как мы указывали отступы, как все это комбинировалось с учетом БЭМа?

2022-12-10 17:40 UTC, wrgraff commented on source/sass/global/variables.scss
> +$font-main: oswald, arial, sans-serif;
Обычно делают наоборот в роли основного шрифта более простой, которым пишутся обычные параграфы текста.
А более кричащий подключают по мере необходимости.

2022-12-10 17:40 UTC, wrgraff commented on source/sass/blocks/specifications.scss
> +}
Шрифт и цвета — наследуемые свойства. Зачем писать их для каждого элемента, если можно написать для всего блока и не повторяться?

```suggestion
.specifications {
  font-family: $font-second;
  font-weight: 400;
  font-size: 12px;
  line-height: 16px;
  color: $color-grey-600;
}

.specifications__meaning {
  margin: 0;
}
```

2022-12-10 17:40 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> +  display: block;
Зачем нам отображение переключать?
Мы не приступаем к сеткам. Это излишне

2022-12-10 17:40 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> +  border-top: 1px solid $color-grey-100;
Рамка это декор. До декора еще сколько разделов там... 2 или 3?

2022-12-10 17:40 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> +  margin: 0;
Отступы для БЭМ-блоков лучше бы конечно не сбрасывать

2022-12-10 17:40 UTC, wrgraff commented on source/sass/blocks/selection.scss
> +.selection__button {
Почему эта кнопка не смиксована в разметке с блоком `button`?
Зачем нам прописывать столько свойств, которые можно было бы получить оттуда?

2022-12-10 17:40 UTC, wrgraff commented on source/sass/blocks/selection.scss
> +  padding-bottom: 25px;
Почему я против расставления отступов на этом этапе?
Потому что они расставлены неправильно, и чтобы объяснить почему мне нужно переходить к теме сеток.

2022-12-10 17:40 UTC, wrgraff commented on source/sass/blocks/form-program.scss
> +  margin: 0%0;
А это что за чудо

2022-12-12 15:54 UTC, Kris-js commented on source/form.html
> +          <legend class="form-group__title form-options__title">Дополнительно</legend>
на `form-options__title` исправила

2022-12-12 15:55 UTC, Kris-js commented on source/form.html
> +          <button class="button form__button" type="submit">Отправить заявку</button>
Исправила

2022-12-12 16:00 UTC, Kris-js commented on source/index.html
>          </h2>
Ага подправила

2022-12-12 16:01 UTC, Kris-js commented on source/sass/style.scss
> +@import "./blocks/copyright.scss";
Согласна, переделала

2022-12-12 16:15 UTC, Kris-js commented on source/sass/global/fonts.scss
> +  font-family: "oswald";
Исправила

2022-12-13 06:35 UTC, Kris-js commented on source/sass/global/fonts.scss
> +}
Исправила

2022-12-13 06:39 UTC, Kris-js commented on source/sass/global/fonts.scss
> +    url("../../fonts/oswald/oswaldregular.woff") format("woff");
Исправила

2022-12-13 06:40 UTC, Kris-js commented on source/sass/global/global.scss
> +  color: #000000;
Убрала)

2022-12-13 06:42 UTC, Kris-js commented on source/sass/global/variables.scss
> +$color-green-1000: #68b738;
Исправила на 500

2022-12-13 06:44 UTC, Kris-js commented on source/sass/global/variables.scss
> +$color-white: #ffffff;
Поменяла

2022-12-13 07:45 UTC, Kris-js commented on source/sass/global/variables.scss
> +$font-second: lato, arial, sans-serif;
Исправила с ковычками

2022-12-13 07:48 UTC, Kris-js commented on source/sass/global/variables.scss
> +$font-main: oswald, arial, sans-serif;
Я просто выбрала основной тот, который чаще встречается на сайте

2022-12-13 07:51 UTC, Kris-js commented on source/sass/blocks/specifications.scss
> +}
Согласна, подправила

2022-12-13 07:53 UTC, Kris-js commented on source/sass/blocks/site-list.scss
> +  display: block;
Убрала

2022-12-13 08:13 UTC, Kris-js commented on source/sass/blocks/selection.scss
> +.selection__button {
Смиксовала вроде

2022-12-13 11:11 UTC, Kris-js commented on source/sass/blocks/selection.scss
> +  padding-bottom: 25px;
Убрала

2022-12-13 11:12 UTC, Kris-js commented on source/sass/blocks/site-list.scss
> +  margin: 0;
убрала

2022-12-13 11:17 UTC, Kris-js commented on source/sass/blocks/form-program.scss
> +  margin: 0%0;
Мурзилка, наверно, лапой задел))

2022-12-13 16:39 UTC, arturtrifonov commented on source/form.html
> +          <legend class="form-options__title form-options__title">Дополнительно</legend>
Получилось 2 класса элемента `form-options__title`

2022-12-13 16:39 UTC, arturtrifonov commented on source/sass/global/variables.scss
> +$color-green-500: #68b738;
А почему зеленый то между белым и серыми градациями к черному )

2022-12-13 16:39 UTC, arturtrifonov commented on source/sass/global/variables.scss
> +$font-main: oswald, arial, sans-serif;
Это не лучшая стратегия.
Захочет кто-то добавить на сайт новый блок без всяких классов и прочего — а он у него будет идти весь этим "орущим" жирным шрифтом, который создан для расстановки акцентов.

Поэтому правильно выбирать не по частоте, а по тому, каким шрифтом оформлен обычный параграф текста.
<img width="605" alt="изображение" src="https://user-images.githubusercontent.com/37917037/207391690-9f59cff5-87e8-4fac-9bf7-ae84af0d4bde.png">

2022-12-13 16:41 UTC, arturtrifonov commented on source/sass/blocks/form-program.scss
> +  margin: 0%0;
Он лапами задевает, а у нас тесты падают потом =)

2022-12-13 16:41 UTC, wrgraff approved these changes

2022-12-13 16:41 UTC, merged

2022-12-13 18:32 UTC, Kris-js commented on source/sass/global/variables.scss
> +$font-main: oswald, arial, sans-serif;
Согласна, поменяла)