Module4 task1
htmlacademy-adaptive/1390101-cat-energy-27 pull request #4
Opened 2022-12-16 14:03 UTC by Kris-js

2022-12-17 17:50 UTC, wrgraff requested changes
Повторяешь некоторые ошибки, которые мы обговаривали на тренировочном проекте.
Но стало гораздо меньше сеток с расписанными рядами, чем в прошлый раз =)

Не старайся сделать много. Давай закончим с главной, потом — к каталогу.

2022-12-17 17:50 UTC, arturtrifonov commented on source/catalog.html
> +      <p class="additional__text present">Закажите все и получите чехол для кота в подарок!</p>
Почему не так? Логично же )
```suggestion
      <p class="additional__present present">Закажите все и получите чехол для кота в подарок!</p>
```

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/container.scss
> +  width: auto;
Зачем писать? Значение `auto` и так по умолчанию

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/container.scss
> +    width: auto;
Там и так было значение по умолчанию — а переназначать его на такое же зачем?

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/container.scss
> +    width: 1220px;
Получается странное. У тебя `$desktop-width` равняется 1200px. И получается, что как только ширина окна достигает 1200 точек ты ставишь ширину в 1220 точек.
А как 1220 влезет в 1200?

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/page.scss
> +  min-width: auto;
Почему auto? У нас разве нет минимальной рабочей ширины?
А если бы ее не было — зачем такое писать?

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/container.scss
> +}
Отмечу здесь, так как в файле `main-container.scss` изменений нет. А должны быть!
Вот зачем эти отступы нужны?
https://github.com/htmlacademy-adaptive/1390101-cat-energy-27/blob/8db1a59bca4ff4fc8a9afb8a0ce6ece959517486/source/sass/blocks/main-container.scss#L1-L4

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/main-header.scss
> +  flex-direction: column;
Мы ведь обсуждали это. Если блоки идут друг за другом: с какой целью включается колоночный флекс?

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/main-header.scss
> +    justify-content: space-between;
У тебя в этой сетке должно участвовать 2 картинки (внутри ссылки) и кнопка открытия меню.
Без правок в разметку ты это вряд ли сделаешь.

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/main-nav.scss
> +  justify-content: space-between;
У тебя кнопка не в том месте в разметке, ты ее вот этим кодом ставишь в линию со списком меню.
Зачем?

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/main-nav.scss
> +  margin: 0 auto;
А центрировать этот блок для чего? Он распределяется на всю ширину экрана:
<img width="557" alt="изображение" src="https://user-images.githubusercontent.com/37917037/208251798-45b717ee-ac72-4486-8a62-95b15a9f003d.png">

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/selection.scss
> +  flex-direction: column;
Мы же обсуждали этот подход, еще на тренировочном нашем сайте, что не нужно создавать флекс ради того, чтобы поставить элементы друг под другом, потому что они и так располагаются таким образом без флекса

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/offer.scss
> +  flex-direction: column;
?

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/offer.scss
> +// Не срабатывает на десктопе
Какой элемент у нас родительский для `.offer__inner`?

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/offer.scss
> +    display: flex;
2 равные колонки. Почему это флекс, а не грид!?

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/offer.scss
> +  }
Зачем ты жестко задаешь ширину им всем?
При чем это уже внутри карточек самому содержимому. какой замысел?

https://github.com/htmlacademy-adaptive/1390101-cat-energy-27/blob/8db1a59bca4ff4fc8a9afb8a0ce6ece959517486/source/sass/blocks/offer.scss#L29-L31
https://github.com/htmlacademy-adaptive/1390101-cat-energy-27/blob/8db1a59bca4ff4fc8a9afb8a0ce6ece959517486/source/sass/blocks/offer.scss#L44-L46
https://github.com/htmlacademy-adaptive/1390101-cat-energy-27/blob/8db1a59bca4ff4fc8a9afb8a0ce6ece959517486/source/sass/blocks/offer.scss#L57-L59

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/operation.scss
> +    justify-content: space-between;
Почему это флекс, а не грид?
Равные колонки создаются у нас, на планшете — 2, на десктопе — 4.
Мы же все это разбирали, ты мне правильно называла во всех случаях что именно применять выгоднее. А тут ставишь флекс везде

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/operation.scss
> +  flex-direction: column;
Здесь то нам зачем флекс?
Тут вообще `section` содержит только `div.operation__wrapper.container`. Зачем его флексить?

Зачем нужен колоночный флекс?
У него очень узкая зона применения: для растягивания по вертикали элемента внутри объекта, который может быть выше контента. Или для прижимания элемента к низу блока с заданной высотой.
Таких случаев в этом сайте если постараться — можно найти 2 штуки. У тебя этот колоночный флекс применен раз 20.

2022-12-17 17:50 UTC, arturtrifonov commented on source/sass/blocks/example.scss
> +  grid-template-columns: 1fr 1fr;
Где на мобильнике тут 2 колонки?
Там на десктопе слайдер с котами можно (и нужно) поставить справа от контента. До этого момента тебе достаточно одной колонки

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/example.scss
> +// второй раз переписываю и снова запуталась здесь с сеткой
Потому что ты создала 2 колонки и теперь ставишь всем элементам распределение чтобы они были сразу в обеих колонках.
Включи 2 колонки только на десктопе. Помести слайдер в правую и займи им несколько рядов. Остальной контент — в левую. Вот и все.

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/example.scss
> +    flex-direction: row;
`row` это значение по умолчанию, его писать не нужно.
Это привычка видимо от переназначения флексовых колонок.

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/copyright.scss
> +  // почему не расходится в стороны
Какие элементы ты пытаешься расставить?
Какой у них родительский элемент?

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/map.scss
> +    display: flex;
А до этого какой `display`?

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/map.scss
> +    flex-direction: row;
А до этого какой `flex-direction`?

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/map.scss
> +    justify-content: space-between;
А до этого какой `justify-content`?

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/map.scss
> +  justify-content: space-between;
Когда ставишь `space-between` нужно всегда помнить о том, что элементы, которые находятся внутри этого флекса, могут соприкоснуться, а контент при этом может "слипнуться". Надо это заранее предотвращать такой случай

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
> +}
Вот тут максимально правильно по сравнению с другими случаями применена сетка

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/container.scss
> +.container {
А где центрирование то в итоге?

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/product.scss
> +    justify-content: space-between;
Почему это флекс?

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/product.scss
> +    margin-bottom: 75px;
Между какими элементами блока `product` этот отступ ставит расстояние?
Или это отступ от самого блока, который просто перенесен на последний элемент, который его содержит?

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/product.scss
> +    width: 324px;
Ну резину так точно не сделать. Ширину элементов должна определять сетка и не в фиксированной величине

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/product-card.scss
> +  grid-template-rows: 1fr 1fr min-content;
А ряды то здесь зачем...
Что мешает оставить карточкам формирование элементов так, как они идут? Ты знаешь, как себя с такой настройкой рядов поведут карточки в случае, если одна из них станет выше других?

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/product-card.scss
> +  grid-column: 1/3;
На планшете расположение в сетке меняется. Нужно или переназначать или писать это правило сразу только для мобильного (у нас даже есть под него брейкпоинт)

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> +    width: 460px;
Ширина при резиновой верстке не подходит.
меню должно занимать какое-то положение в сетке, которая пропорционально меняется. Меню там при этом занимает свое место.

Если где-то нужна будет ширина — это уже для фикса переполнения или каких-то таких моментов. Сейчас она пока не должна бы всплывать

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/social.scss
> +  height: 22px;
У нас же иконки разного размера

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/specifications.scss
> +  // Почему не разьезжаются?(
Потому что сам элемент сжат по ширине внутри `.product-card`, так как у того стоит `justify-items: center;`

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/slider-cat.scss
> +  justify-content: center;
Почему центр, зачем?

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/additional.scss
> +.additional {
У этого блока потерялась обертка с центрированием

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/additional.scss
> +    grid-template-columns: 1fr min-content;
Сетка не соответствует макету, у нее продуманное соотношение сторон колонок:
<img width="938" alt="изображение" src="https://user-images.githubusercontent.com/37917037/208254446-18a88697-6ef2-4bb5-8f26-07d1d3fb0324.png">

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/additional.scss
> +    justify-content: space-between;
Тут тоже: слишком простое правило для контента, он сложнее распределеяется.
С другой стороны, это скорее мелкая сетка

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/form-options.scss
> +    grid-template-rows: 1fr 1fr;
С какой целью ряды поставлены?

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/form-program.scss
> +    grid-column: 2/3;
Желательно, чтобы управление положением элемента в гриде шло через БЭМ-элемент того БЭМ-блока, на котором этот грид задан

2022-12-17 17:50 UTC, wrgraff commented on source/sass/blocks/form.scss
> +  }
Вообще, она более-менее вписана в сетку, это не просто какая-то рандомная ширина в пикселях:
<img width="479" alt="изображение" src="https://user-images.githubusercontent.com/37917037/208254673-4f665d06-3032-4b5c-bc80-e14d29da49da.png">
<img width="872" alt="изображение" src="https://user-images.githubusercontent.com/37917037/208254686-49a9be83-48e7-4e6c-83af-27abedd1d9c9.png">

2022-12-19 14:42 UTC, Kris-js commented on source/catalog.html
> +      <p class="additional__text present">Закажите все и получите чехол для кота в подарок!</p>
Согласна)

2022-12-19 14:52 UTC, Kris-js commented on source/sass/blocks/container.scss
> +  width: auto;
исправила

2022-12-19 14:52 UTC, Kris-js commented on source/sass/blocks/container.scss
> +    width: auto;
исправила

2022-12-19 15:00 UTC, Kris-js commented on source/sass/blocks/container.scss
> +    width: 1220px;
Не понимаю откуда я взяла эту ширину) Исправила на `width: 1200px;`

2022-12-19 15:37 UTC, Kris-js commented on source/sass/blocks/container.scss
> +}
Да, все ведь переделала отдельным классом `container`

2022-12-22 19:15 UTC, Kris-js commented on source/sass/blocks/page.scss
> +  min-width: auto;
Убрала

2022-12-22 19:15 UTC, Kris-js commented on source/sass/blocks/main-header.scss
> +  flex-direction: column;
+

2022-12-22 19:16 UTC, Kris-js commented on source/sass/blocks/main-header.scss
> +    justify-content: space-between;
+

2022-12-22 19:16 UTC, Kris-js commented on source/sass/blocks/main-nav.scss
> +  justify-content: space-between;
+

2022-12-22 19:16 UTC, Kris-js commented on source/sass/blocks/main-nav.scss
> +  margin: 0 auto;
+

2022-12-22 19:25 UTC, Kris-js commented on source/sass/blocks/selection.scss
> +  flex-direction: column;
+

2022-12-22 19:42 UTC, Kris-js commented on source/sass/blocks/offer.scss
> +  flex-direction: column;
+

2022-12-22 19:54 UTC, Kris-js commented on source/sass/blocks/offer.scss
> +// Не срабатывает на десктопе
+

2022-12-22 19:54 UTC, Kris-js commented on source/sass/blocks/offer.scss
> +    display: flex;
теперь грид)

2022-12-22 19:55 UTC, Kris-js commented on source/sass/blocks/offer.scss
> +  }
+

2022-12-22 20:10 UTC, Kris-js commented on source/sass/blocks/operation.scss
> +    justify-content: space-between;
+

2022-12-22 20:10 UTC, Kris-js commented on source/sass/blocks/operation.scss
> +  flex-direction: column;
+

2022-12-23 04:08 UTC, Kris-js commented on source/sass/blocks/example.scss
> +// второй раз переписываю и снова запуталась здесь с сеткой
+

2022-12-23 04:08 UTC, Kris-js commented on source/sass/blocks/example.scss
> +    flex-direction: row;
+

2022-12-23 04:08 UTC, Kris-js commented on source/sass/blocks/copyright.scss
> +  // почему не расходится в стороны
+

2022-12-23 16:12 UTC, wrgraff approved these changes
Я думаю, ты легко пофиксишь что я написал тут и можно сразу присылать страницу каталога

2022-12-23 16:12 UTC, wrgraff commented on source/sass/blocks/container.scss
> +    width: 1200px;
Да нет, вроде правильно было: 1220 пикселей ширина контентной области, да.

2022-12-23 16:12 UTC, wrgraff commented on source/sass/blocks/container.scss
>      padding: 0 110px;
Вот этот отступ — это размер до края на экране 1440 точек:
```110px -- 1220px -- 110px```

Тебе его даже писать не надо. У тебя 1220 отцентрируется, а по краям освободится 110 пикселей.
Но если и писать, то:
- или не на центровщик
- или центровщик должен включать в свой размер отступы

2022-12-23 16:12 UTC, wrgraff commented on source/index.html
> +  <header class="main-header container">
Логично, но нам нужен несколько специфический контейнер для хэдера, так как на мобильнике хэдер нужен без отступов

2022-12-23 16:12 UTC, wrgraff commented on source/index.html
> +          <div class="slider-cat__wrapper container">
Вот тут у тебя `container` внутри `container`'а получается.
Чем это плохо?
Ну, ты вписываешь этот блок на десктопе в правую половину, а у него огромная ширина. И сетка ломается. Это надо поправить

2022-12-23 16:13 UTC, wrgraff commented on source/sass/blocks/container.scss
> +    width: 1220px;
Надо поменять брейкпоинт, ширина то правильная вроде была )

2022-12-26 07:26 UTC, Kris-js commented on source/sass/blocks/product.scss
> +    justify-content: space-between;
Теперь грид

2022-12-26 07:27 UTC, Kris-js commented on source/sass/blocks/product.scss
> +    width: 324px;
+

2022-12-26 07:27 UTC, Kris-js commented on source/sass/blocks/product-card.scss
> +  grid-template-rows: 1fr 1fr min-content;
+ ряды убрала

2022-12-26 07:37 UTC, Kris-js commented on source/sass/blocks/product-card.scss
> +  grid-column: 1/3;
Добавила медиа планшета

2022-12-26 07:38 UTC, Kris-js commented on source/sass/blocks/site-list.scss
> +    width: 460px;
ок, поняла про ширину

2022-12-26 07:43 UTC, Kris-js commented on source/sass/blocks/social.scss
> +  height: 22px;
Нужно `svg` же вставлять для смены состояний? Или вообще убрать пока и оставить только размер ссылки?

2022-12-26 07:44 UTC, Kris-js commented on source/sass/blocks/specifications.scss
> +  // Почему не разьезжаются?(
Все увидела, исправила)

2022-12-26 07:44 UTC, Kris-js commented on source/sass/blocks/slider-cat.scss
> +  justify-content: center;
+

2022-12-26 07:48 UTC, Kris-js commented on source/sass/blocks/additional.scss
> +.additional {
Добавила `div`

2022-12-26 12:35 UTC, Kris-js commented on source/sass/blocks/form-options.scss
> +    grid-template-rows: 1fr 1fr;
Вроде все и без них все работает

2022-12-26 12:58 UTC, Kris-js commented on source/sass/blocks/form-program.scss
> +    grid-column: 2/3;
Я понимаю, но пока не знаю как исправить. Создать еще один класс с `order-form`?

2022-12-26 19:50 UTC, wrgraff requested changes
Так же обрати внимание, что проверку по линтеру проект не прошел

2022-12-26 19:50 UTC, arturtrifonov commented on source/sass/blocks/container.scss
> +    width: 1300px;
Ну опять тоже самое: брейкпоинт 1220px, ширина — 1300px.
Ну как 1300 влезет в 1220?

2022-12-26 19:50 UTC, arturtrifonov commented on source/sass/blocks/container.scss
> -    padding: 0 110px;
Получается, отступ остается от планшетной ширины: 30px.
30 + 30 + 1220 = 1280. Получается, не совпадает

2022-12-26 19:50 UTC, arturtrifonov commented on source/sass/blocks/main-header.scss
> +    padding: 0 30px;
Здесь же должно вернуться ограничение ширины

2022-12-26 19:50 UTC, arturtrifonov commented on source/sass/blocks/main-header.scss
> +    padding: 0 110px;
Вроде бы в контейнере этот отступ убрали — откуда он тут всплыл?
Размер хэдера не будет соответствовать размеру контента

2022-12-26 19:50 UTC, wrgraff commented on source/sass/blocks/map.scss
> +    min-height: 100%;
А зачем у тебя в атрибутах самого iframe стоит высота 450, если тебе везде по сути нужно не более 400?

2022-12-26 19:50 UTC, wrgraff commented on source/sass/blocks/map.scss
> +// Странно, что карта на планшетной версии не растягивается
Почему странно? У нее стоит ширина в атрибуте `width`, она ее и занимает.
На десктопе ее переписывает `min-width`, на планшете — ничего не переписывает

2022-12-26 19:50 UTC, wrgraff commented on source/sass/blocks/additional.scss
> +    grid-template-columns: 1fr 1fr 1fr 1fr min-content;
А `min-content` то тут зачем?
Он просто создает нулевую колонку по размеру

2022-12-26 19:50 UTC, wrgraff commented on source/sass/blocks/additional.scss
> +    grid-column: 1/3;
Между 3 и 4 колонкой линия идет 4-я

2022-12-26 19:50 UTC, wrgraff commented on source/sass/blocks/additional.scss
> +    grid-column: 3/4;
Можно вообще не указывать ничего: в оставшуюся колонку оно само встанет

2022-12-27 15:49 UTC, Kris-js commented on source/sass/blocks/container.scss
> +    width: 1220px;
с шириной вроде разобрались

2022-12-27 15:51 UTC, Kris-js commented on source/sass/blocks/main-header.scss
> +  flex-direction: column;
исправила на гриды

2022-12-27 15:51 UTC, Kris-js commented on source/sass/blocks/operation.scss
> +    justify-content: space-between;
гриды

2022-12-27 16:29 UTC, Kris-js commented on source/sass/blocks/product.scss
> +    margin-bottom: 75px;
Был отступ от блока, но я его пока убрала

2022-12-28 07:57 UTC, wrgraff approved these changes
Футер надо еще отцентрировать не забыть

2022-12-28 07:57 UTC, wrgraff commented on source/sass/blocks/form-options.scss
> +    grid-template-rows: 1fr 1fr;
Тогда зачем они в коде то?

2022-12-28 07:57 UTC, merged