дорабатывает графику всех страниц
htmlacademy-adaptive/1390101-cat-energy-27 pull request #6
Opened 2023-01-22 21:47 UTC by Kris-js

2023-01-23 12:30 UTC, wrgraff requested changes
В форме то полоски то почини тоже
<img width="1510" alt="изображение" src="https://user-images.githubusercontent.com/37917037/214037358-1a8f6f5e-ccc0-4ab1-b733-698771e6094f.png">

2023-01-23 12:30 UTC, arturtrifonov commented on source/index.html
> +      </picture>
Картинка меняется, но не меняются размеры.
Нужно через стили задать иконке ширину и высоту, которые у нее должны быть на планшете и на десктопе.

2023-01-23 12:30 UTC, arturtrifonov commented on source/index.html
> +            srcset="img/index-can-mobile@2x.png" alt="Пример питания для котов Кэт Энерджи Про с курицей 500 грамм">
Пропустила точки в адресах для 2x картинок
Картинки из-за ошибки в пути могут не отображаться на экранах с ретиной

2023-01-23 12:30 UTC, arturtrifonov commented on source/index.html
> +                  alt="Изображение кота до изменений">
Как и логотипу котам нужно прописать в стилях размер.
Иначе они берут размеры из атрибутов `width` и `height`, а нас это не устраивает, так как картинки меняют размер.

2023-01-23 12:30 UTC, arturtrifonov commented on source/index.html
> +                  srcset="./img/cat-slider-big-tablet@1x.png, img/cat-slider-big-tablet@2x.png 2x">
Точка тоже потерялась тут

2023-01-23 12:30 UTC, wrgraff commented on source/index.html
> +              <img src="./img/cat-slider-small.png" width="280" height="256" srcset="./img/cat-slider-small@2x.png 2x"
А почему для первого кота есть тег `<picture>` для кадрированной картинки, а для этого кота нет?

2023-01-23 12:30 UTC, wrgraff commented on source/index.html
> +          <source media="(min-width:768px)" srcset="./img/index-can-tablet.png, /img/index-can-tablet@2.png 2x">
Куда потерялся `x`?
Смотри вообще через девтулз картинки на 3х разрешениях и в двух вариантах плотности
```suggestion
          <source media="(min-width:1300px)" srcset="./img/index-can-desktop.png, /img/index-can-desktop@2x.png 2x">
          <source media="(min-width:768px)" srcset="./img/index-can-tablet.png, /img/index-can-tablet@2x.png 2x">
```

2023-01-23 12:30 UTC, wrgraff commented on source/catalog.html
> +
Что за дырка такая

2023-01-23 12:30 UTC, wrgraff commented on source/sass/blocks/present.scss
> +    background-image: url("../img/background-cat-catalog@2x.png");
Браузер сам по себе не умеет отличать картинки для ретины от обычных картинок. Все эти фокусы в именовании с `@2x` не дают нам никакой автоматизации и магии.

Медиа-запрос `(min-resolution: 2dppx)` тоже для браузера не дает дополнительной инструкции в плане размещения и размера картинки, он всего лишь применяет указанные в запросе стили.

Поэтому, если закинуть в фон картинку в 2 раза больше — она и отобразится в 2 раза больше. Поэтому, обязательно нужно прописать `background-size`.

2023-01-23 12:30 UTC, wrgraff commented on source/sass/blocks/selection.scss
> +        background-image: url("../img/index-background-desktop@2x.png");
Аналогичная ситуация: фону не задан размер, картинка грузится в полном размере и ее даже не видно в квадрате.

2023-01-23 19:00 UTC, Kris-js commented on source/index.html
> +      </picture>
ага поменяла

2023-01-23 19:04 UTC, Kris-js commented on source/index.html
> +            srcset="img/index-can-mobile@2x.png" alt="Пример питания для котов Кэт Энерджи Про с курицей 500 грамм">
везде вроде добавила

2023-01-23 19:29 UTC, Kris-js commented on source/index.html
> +              <img src="./img/cat-slider-small.png" width="280" height="256" srcset="./img/cat-slider-small@2x.png 2x"
Добавила

2023-01-23 19:31 UTC, Kris-js commented on source/catalog.html
> +
ой

2023-01-24 09:12 UTC, wrgraff requested changes

2023-01-24 09:12 UTC, wrgraff commented on source/index.html
> +                  srcset="./img/cat-slider-small-tablet.png, ./img/cat-clider-small-tablet@2x.png 2x">
Опечатка
```suggestion
                  srcset="./img/cat-slider-small-tablet.png, ./img/cat-slider-small-tablet@2x.png 2x">
```

2023-01-24 09:12 UTC, wrgraff commented on source/sass/blocks/slider-cat.scss
> +  }
Вот здесь не нужны размеры, они ломают сетку. Оба контейнера с картинками получают размер отсюда, а должны как раз получать его от грида

2023-01-24 09:12 UTC, arturtrifonov commented on source/sass/blocks/slider-cat.scss
> +    height: 512px;
А вот тут правильно: сами картинки должны иметь размер, а контейнер, который их содержит — нет

2023-01-24 09:12 UTC, merged