Second try
htmlacademy-adaptive/1390101-cat-energy-27 pull request #8
Opened 2023-01-28 12:23 UTC by Kris-js

2023-01-28 13:16 UTC, wrgraff requested changes
А что вообще файл `button.scss` делает в global? Это не глобальный стиль, а БЭМ-блок.

- Слайдер у котов должен реагировать на наведение и захват. Сделай пока хотя бы то, что не касается SVG. (я кстати просил сделать картинкой только стрелочки, без кругляка).
- Логотип Академии в футере тоже надо сделать. Там часть стилей — только прозрачность.

2023-01-28 13:16 UTC, arturtrifonov commented on source/catalog.html
> +          <a class="copyright__link" href="https://up.htmlacademy.ru/adaptive/27">
Ссылка должна быть не на страницу курса, а на лендинг интенсива:

> [3.8.](https://up.htmlacademy.ru/adaptive/27/project/cat-energy#cat-energy-3-8) Логотип и текст HTML Academy в футере являются ссылкой на [лендинг интенсива «HTML и CSS. Адаптивная вёрстка и автоматизация»](https://htmlacademy.ru/intensive/adaptive).

2023-01-28 13:16 UTC, arturtrifonov commented on source/sass/global/button.scss
> +  color: $color-white 0.3;
Так не пишется, для конвертирования текст в прозрачный нужно применять `rgba()`.
Это — не работает

2023-01-28 13:16 UTC, wrgraff commented on source/sass/blocks/main-header.scss
> +
Надо сделать так, чтобы логотип реагировал на взаимодействие только если на нем действительно есть ссылка.
Неактивная ссылка не должна реагировать

2023-01-28 13:16 UTC, wrgraff commented on source/sass/blocks/site-list.scss
> +}
Активный пункт меню не должен реагировать

2023-01-28 13:16 UTC, wrgraff commented on source/sass/blocks/field.scss
> +.field__input:active {
Нет, это не состояние `:active`.
Это состояние фокуса, там довольно явно это прописано в макете:
<img width="828" alt="изображение" src="https://user-images.githubusercontent.com/37917037/215268025-7012dfba-0d2e-4a0a-8cad-f55fda7f6f34.png">

2023-01-28 13:16 UTC, wrgraff commented on source/sass/blocks/field.scss
> +  border: 2px solid $color-grey-600;
Ты меняешь толщину рамки, в результате чего по клику геометрия элемента меняется и текст внутри смещается.
так быть не должно. Попробуй рисовать рамку через `outline` (как и делается при фокусе)

2023-01-28 13:16 UTC, wrgraff commented on source/sass/blocks/field.scss
> +.field__input:invalid {
Надо заменить на user-invalid или вообще создать отдельный модификатор для состояния ошибки.
При таком решении поля по умолчанию подсвечиваются красным:
<img width="1259" alt="изображение" src="https://user-images.githubusercontent.com/37917037/215268143-9dface33-2f53-4846-aab8-a1a9334223fd.png">

2023-01-28 13:16 UTC, wrgraff commented on source/sass/blocks/radio.scss
> +  }
Все еще не хватает состояния фокуса.
В состоянии фокуса находится сам инпут, поэтому его нужно ловить и стилизовать так же, как и состояние `:checked`

2023-01-28 13:16 UTC, wrgraff commented on source/sass/blocks/checkbox.scss
> +  }
Откуда и зачем взялись эти размеры?
Выглядит так, что они все сломали:
<img width="202" alt="изображение" src="https://user-images.githubusercontent.com/37917037/215268303-8a1e7091-b2bc-4c92-8f5c-3e6b41694a69.png">

2023-01-28 13:16 UTC, wrgraff commented on source/sass/blocks/checkbox.scss
> +}
Как и с radio не хватает состояния фокуса

2023-01-28 16:34 UTC, Kris-js commented on source/catalog.html
> +          <a class="copyright__link" href="https://up.htmlacademy.ru/adaptive/27">
+

2023-01-28 16:43 UTC, Kris-js commented on source/sass/blocks/field.scss
> +.field__input:invalid {
создала отдельный модификатор

2023-01-30 08:25 UTC, wrgraff commented on source/catalog.html
> +  <link rel="preload" href="css/style.css" as="style" crossorigin="anonymous">
А откуда ты взяла предзагрузку стилей? По заданию только шрифты же требуются

2023-01-30 08:25 UTC, wrgraff commented on source/form.html
> +  <link rel="preload" href="img/index-cat@2x.png" as="image" crossorigin="anonymous">
Это вообще что тут делает... Картинка с главной предзагружается на странице формы. Зачем??

2023-01-30 08:25 UTC, wrgraff commented on source/catalog.html
> +  <link rel="preload" href="fonts/lato/Lato-Regular.woff2" as="font" crossorigin="anonymous">
Почему шрифт с заглавными буквами?
Разбирали же, что не должно быть заглавных букв в именах файлов...

2023-01-30 08:25 UTC, wrgraff commented on source/index.html
> +  <link rel="preload" href="fonts/lato/Lato-Regular.woff2" as="font" crossorigin="anonymous">
Кроме этого шрифта надо предзагрузить еще oswaldregular.
2 шрифта должно быть. Откуда все остальное вылезло?

2023-01-30 20:49 UTC, wrgraff approved these changes

2023-01-30 20:49 UTC, merged